# Generated by Django 4.1 on 2022-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('select', models.CharField(max_length=100)),
            ],
        ),
    ]
