# Generated by Django 4.1 on 2022-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='message',
            field=models.TextField(default='my service', max_length=1000),
        ),
    ]
