# Generated by Django 4.1 on 2022-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecha_app', '0002_userform_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='userEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
    ]
